name: Go CI
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 # Action to check out your repository's code

      - name: Set up Go
        uses: actions/setup-go@v5 # Action to set up a specific Go version
        with:
          go-version: 1.25 # Specify the version of Go to use

      - name: Build
        run: go build -v ./... # Build your Go project

      - name: Test
        run: go test -v ./... # Run all tests in the project
